services:
  andrei_php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/html
    ports:
      - "81:80"

  andrei_datab:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: andrei
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3309:3306"

  andrei_phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: andrei_datab
      PMA_PORT: 3306
      PMA_USER: andrei
      PMA_PASSWORD: password
    ports:
      - "82:80"

volumes:
  db_data: